### ISSUE TITLE
Timeout when parsing very large files

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-datastore#149]
#147 sets timeout to be 180 seconds. However, `usaid-998` times out before then (it is 41.5 MB)

**Comment by markbrough** [comment]
```
Traceback (most recent call last):
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/rq/worker.py", line 975, in perform_job
    rv = job.perform()
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/flask_rq2/job.py", line 41, in perform
    return super(FlaskJob, self).perform()
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/rq/job.py", line 696, in perform
    self._result = self._execute()
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/rq/job.py", line 719, in _execute
    return self.func(*self.args, **self.kwargs)
","  File "/home/admin/iati-datastore/iati_datastore/iatilib/crawler.py", line 250, in update_activities
    parse_resource(resource)
","  File "/home/admin/iati-datastore/iati_datastore/iatilib/crawler.py", line 202, in parse_resource
    parse_activity(new_identifiers, old_xml, resource)
","  File "/home/admin/iati-datastore/iati_datastore/iatilib/crawler.py", line 185, in parse_activity
    db.session.flush()
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 163, in do
    return getattr(self.registry(), name)(*args, **kwargs)
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2536, in flush
    self._flush(objects)
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2678, in _flush
    transaction.rollback(_capture_exception=True)
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2638, in _flush
    flush_context.execute()
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 245, in save_obj
    insert,
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 1136, in _emit_insert_statements
    statement, params
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
","  File "/usr/lib/python3.6/encodings/utf_8.py", line 15, in decode
    def decode(input, errors='strict'):
","  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/rq/timeouts.py", line 64, in handle_death_penalty
    '({0} seconds)'.format(self._timeout))
","rq.timeouts.JobTimeoutException: Task exceeded maximum timeout value (180 seconds)
```

**Comment by andylolz** [comment]
I think #147 actually fixes this.

```python
queue.enqueue(
  update_activities, args=(dataset_name,),
  result_ttl=0, timeout=100000)
```

^^ `timeout=100000` was being ignored by rq here, because in the upgrade to rq v1, the keyword argument was changed. So the default timeout of 180 seconds was being used.

#147 should fix this, by instead specifying the correct keyword argument `job_timeout`.

**Comment by markbrough** [comment]
Yup confirm this is fixed!
