### ISSUE TITLE
Parsing error on files with unusual characters

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-datastore#154]
Failed to parse XML file `undp-bra`: https://datastore.codeforiati.org/api/1/error/dataset/undp-bra/

The file looks fine to me - I suspect the issue is that _open_resource is messing up the character encoding somewhere around here:

https://github.com/codeforIATI/iati-datastore/blob/1faa6b2d59d6a9a821eeffb65ac395b2eea678da/iati_datastore/iatilib/parse.py#L423-L436

It would be good to rationalise `_open_resource()`

## Traceback for UNDP file
```
Traceback (most recent call last):
  File "/home/admin/iati-datastore/iati_datastore/iatilib/parse.py", line 561, in activities
    yield activity(elem, resource=resource, major_version=major_version, version=version)
  File "/home/admin/iati-datastore/iati_datastore/iatilib/parse.py", line 467, in activity
    xml = ET.parse(_open_resource(xml_resource))
  File "src/lxml/etree.pyx", line 3521, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 462
lxml.etree.XMLSyntaxError: PCDATA invalid Char value 3, line 462, column 129

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/iati-datastore/iati_datastore/iatilib/crawler.py", line 250, in update_activities
    parse_resource(resource)
  File "/home/admin/iati-datastore/iati_datastore/iatilib/crawler.py", line 202, in parse_resource
    parse_activity(new_identifiers, old_xml, resource)
  File "/home/admin/iati-datastore/iati_datastore/iatilib/crawler.py", line 163, in parse_activity
    for activity in parse.document(resource.document, resource):
  File "/home/admin/iati-datastore/iati_datastore/iatilib/parse.py", line 568, in activities
    raise XMLError()
iatilib.parse.XMLError
```

**Comment by markbrough** [comment]
https://github.com/codeforIATI/iati-datastore/blob/1faa6b2d59d6a9a821eeffb65ac395b2eea678da/iati_datastore/iatilib/test/test_parser.py#L18-L21

Argument is a **string (file path)**

NB `parse.document` is (in part) a wrapper for `parse._open_document()`
