### ISSUE TITLE
Budget type can be None

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-datastore#259]
### Describe the bug

When trying to download the following file, an empty CSV file is returned:

https://datastore.codeforiati.org/api/1/access/budget/by_sector.csv?reporting-org=GB-GOV-1&stream=True

In the logs, the following error is captured:
```
Traceback (most recent call last):
  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/werkzeug/wsgi.py", line 506, in __next__
    return self._next()
  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 45, in _iter_encoded
    for item in iterable:
  File "/home/admin/iati-datastore/pyenv/lib/python3.6/site-packages/flask/helpers.py", line 162, in generator
    for item in gen:
  File "/home/admin/iati-datastore/iati_datastore/iatilib/frontend/serialize/csv.py", line 415, in __call__
    row = [accessor(obj) for accessor in self.fields_by_major_version[get_major_version(obj)].values()]
  File "/home/admin/iati-datastore/iati_datastore/iatilib/frontend/serialize/csv.py", line 415, in <listcomp>
    row = [accessor(obj) for accessor in self.fields_by_major_version[get_major_version(obj)].values()]
  File "/home/admin/iati-datastore/iati_datastore/iatilib/frontend/serialize/csv.py", line 705, in wrapper
    return func(t)
  File "/home/admin/iati-datastore/iati_datastore/iatilib/frontend/serialize/csv.py", line 240, in budget_type
    return budget.type.name
AttributeError: 'NoneType' object has no attribute 'name'
```

### To Reproduce

1. Go to the above URL
2. See the eerror

### Expected behaviour

Output should contain all activity-budget-sector rows.

**Comment by markbrough** [comment]
This is probably the underlying cause of #258

**Comment by andylolz** [comment]
Oh nice, good spot!
